#pragma once

#include "core/tokenum.h"

enum e_column_type {
    COLUMN_TYPE_NONE = -1,
    COLUMN_TYPE_RISK,
    COLUMN_TYPE_POSITIVE,
    COLUMN_TYPE_WATER_ACCESS,

    COLUMN_TYPE_SIZE
};
using e_column_type_tokens_t = token_holder<e_column_type, COLUMN_TYPE_RISK, COLUMN_TYPE_SIZE>;

enum e_column_color {
    COLUMN_COLOR_NONE = -1,
    COLUMN_COLOR_PLAIN = 0,
    COLUMN_COLOR_YELLOW = 3,
    COLUMN_COLOR_ORANGE = 6,
    COLUMN_COLOR_RED = 9,
    COLUMN_COLOR_BLUE = 12,
};

enum e_overlay : uint8_t {
    OVERLAY_NONE = 0,
    OVERLAY_WATER = 2,
    OVERLAY_RELIGION = 4,
    OVERLAY_FIRE = 8,
    OVERLAY_DAMAGE = 9,
    OVERLAY_CRIME = 10,
    OVERLAY_ENTERTAINMENT = 11,
    OVERLAY_BOOTH = 12,
    OVERLAY_BANDSTAND = 13,
    OVERLAY_PAVILION = 14,
    OVERLAY_SENET_HOUSE = 15,
    OVERLAY_EDUCATION = 16,
    OVERLAY_SCRIBAL_SCHOOL = 17,
    OVERLAY_LIBRARY = 18,
    OVERLAY_ACADEMY = 19,
    OVERLAY_APOTHECARY = 20,
    OVERLAY_DENTIST = 21,
    OVERLAY_PHYSICIAN = 22,
    OVERLAY_MORTUARY = 23,
    OVERLAY_TAX_INCOME = 24,
    OVERLAY_FOOD_STOCKS = 25,
    OVERLAY_DESIRABILITY = 26,
    OVERLAY_WORKERS_UNUSED = 27,
    OVERLAY_NATIVE = 28,
    OVERLAY_PROBLEMS = 29,
    OVERLAY_RELIGION_OSIRIS = 30,
    OVERLAY_RELIGION_RA = 31,
    OVERLAY_RELIGION_PTAH = 32,
    OVERLAY_RELIGION_SETH = 33,
    OVERLAY_RELIGION_BAST = 34,
    OVERLAY_FERTILITY = 35,
    OVERLAY_BAZAAR_ACCESS = 36,
    OVERLAY_ROUTING = 37,
    OVERLAY_HEALTH = 38,
    OVERLAY_LABOR = 39,
    OVERLAY_COUTHOUSE = 40,
    OVERLAY_BREWERY = 41,
    OVERLAY_LABOR_ACCESS = 42,
    OVERLAY_ENEMIES = 43,
    OVERLAY_CRIMINAL = 44,
    OVERLAY_MALARIA_RISK = 45,
    OVERLAY_ARCHITECT_REACH = 46,
    OVERLAY_ZOO = 47,

    // Enhanced flood basins — sealed contour tint
    OVERLAY_FLOOD_BASIN = 48,

    // Food / goods stocks (house inventory columns)
    OVERLAY_GRAIN = 49,
    OVERLAY_CHICKPEAS = 50,
    OVERLAY_POMEGRANATES = 51,
    OVERLAY_FIGS = 52,
    OVERLAY_MEAT = 53,
    OVERLAY_GAME = 54,
    OVERLAY_POTTERY = 55,
    OVERLAY_JEWELRY = 56,
    OVERLAY_LINEN = 57,

    // Health extras (≠ OVERLAY_MALARIA_RISK)
    OVERLAY_DISEASE = 58,
    OVERLAY_INFECTED_HOUSING = 59,
    OVERLAY_MALARIA = 60,

    // Administration extras (magistrate = OVERLAY_COUTHOUSE; admin problems = OVERLAY_PROBLEMS)
    OVERLAY_WATER_CROSSINGS = 61,
    OVERLAY_EMPTY_HOUSING = 62,

    // Other
    OVERLAY_IRRIGATION = 63,
    OVERLAY_CITY_DEFENSES = 64,
    OVERLAY_HIDE_CLIFFS = 65,

    OVERLAY_SIZE
};
using e_overlay_tokens_t = token_holder<e_overlay, OVERLAY_NONE, OVERLAY_SIZE>;
